left_front:
  - lf_hip_axis
  - lf_upper_joint
  - lf_lower_joint
  - lf_foot_joint

right_front:
  - rf_hip_joint
  - rf_upper_joint
  - rf_lower_joint
  - rf_foot_joint

left_hind:
  - lh_hip_joint
  - lh_upper_joint
  - lh_lower_joint
  - lh_foot_joint

right_hind:
  - rh_hip_joint
  - rh_upper_joint
  - rh_lower_joint
  - rh_foot_joint