"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - lf_hip_axis
          - lf_upper_joint
          - lf_lower_joint
          - rf_hip_joint
          - rf_upper_joint
          - rf_lower_joint
          - lh_hip_joint
          - lh_upper_joint
          - lh_lower_joint
          - rh_hip_joint
          - rh_upper_joint
          - rh_lower_joint

      gains:
        lf_hip_axis : {p: 180, d: 0.9, i: 20}
        lf_upper_joint : {p: 180, d: 0.9, i: 20}
        lf_lower_joint : {p: 180, d: 0.9, i: 20}
        rf_hip_joint : {p: 180, d: 0.9, i: 20}
        rf_upper_joint : {p: 180, d: 0.9, i: 20}
        rf_lower_joint : {p: 180, d: 0.9, i: 20}
        lh_hip_joint : {p: 180, d: 0.9, i: 20}
        lh_upper_joint : {p: 180, d: 0.9, i: 20}
        lh_lower_joint : {p: 180, d: 0.9, i: 20}
        rh_hip_joint : {p: 180, d: 0.9, i: 20}
        rh_upper_joint : {p: 180, d: 0.9, i: 20}
        rh_lower_joint : {p: 180, d: 0.9, i: 20}
